project_id = "bwvtfosrbbkawieanrjd"

[functions.getPersonalizedFeed]
verify_jwt = false

[functions.getPriceStats]
verify_jwt = false

[functions.validate-phone]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.admin-merchants]
verify_jwt = false
